### ISSUE TITLE
!give command - allow to select a user by using @username

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/devchatterbot#121]
When using the !give command it should be possible to preface the token receiver by using the 
@symbol. That way, in twitch chat, you don't have to type out a long and perhaps complicated username but can utilize twitch's autocomplete function that is triggered by typing @ and the first letters of the name you're looking for.

**Comment by benrick** [comment]
I couldn't reproduce this.... Seems to work with the `@`

**Comment by asyncawake** [comment]
Oh, you're right, it works. I mistyped twice, testing that. Shame!
