### ISSUE TITLE
Add basic error logging

### ISSUE THREAD

**Issue by benrick** [DevChatter/devchatterbot#16]
We should add basic error handling and logging. The bot should continue running in nearly all cases of Exceptions. 

Exceptions while running a command, sending or receiving messages, or getting API information should not crash the bot. Each of these should be logged and the bot allowed to continue running.

**Comment by benrick** [comment]
We should likely be using the nuget package `Microsoft.Extensions.Logging.Console`

**Comment by Mackiovello** [comment]
I'd be happy to look at this next week
