### ISSUE TITLE
Add protection against chat ddos attacks 

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/devchatterbot#182]
After witnessing a chat DDOS attack on Fritzsharp's stream recently, I think it would be advisable to be prepared for that in the future. 
The devchatterbot could attempt to recognize such a pattern and put the chat on slow, maybe even temporarily mute the "new follower" soundbyte and gif which will otherwise drown out the streamer.

![image](https://user-images.githubusercontent.com/37850395/40323022-76a7c988-5d34-11e8-8ca0-76bbe7c31fb2.png)
![image](https://user-images.githubusercontent.com/37850395/40323028-7bc3db82-5d34-11e8-90bb-c3602dba55d5.png)

**Comment by benrick** [comment]
It would seem that I always had the email verification protection turned on, and mods could turn on the `/r9kbeta` as-needed. Don't want games with repeating text to mess with people. Like everyone typing `!join` for example.
