### ISSUE TITLE
Update the Configuration.md

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/devchatterbot#201]
The appsettings.json file has changed and the instructions for setting up its contents are not accurate anymore. 

There are now undocumented TwitchClientSettings and some of their names have changed, as well:
  "TwitchClientSettings": {
    "TwitchUsername": "secret",
    "TwitchChannelID": "secret",
    "TwitchBotUserID": "secret",
    "TwitchBotOAuth": "secret",
    "TwitchChannelOAuth": "secret",
    "TwitchChannel": "secret",
    "TwitchClientId": "secret"}

The old Settings were:
  "TwitchClientSettings": {
    "TwitchUsername": "secret",
    "TwitchUserID": "secret",
    "TwitchOAuth": "secret",
    "TwitchChannel": "secret",
    "TwitchClientId": "secret"
  }

**Comment by asyncawake** [comment]
I'm currently working on that, especially now that I've got my secret manager to work (thanks @benrick ) :)

**Comment by benrick** [comment]
How's this PR coming along, @asyncawake ?
