### ISSUE TITLE
Timezone by city - schedule command

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/devchatterbot#202]
As ajukraine suggested in chat, another nice addition would be to get the timezone by city, as in: 
!schedule Berlin or 
!schedule Los Angeles

Whoever wants do to this could use the currently commented-out test in the following file to code against:
https://github.com/DevChatter/devchatterbot/blob/master/src/UnitTests/Core/Commands/ScheduleCommandTests/ProcessShould.cs

**Comment by benrick** [comment]
Resolved by #214
