### ISSUE TITLE
Enforce 24 hour format for UTC.

### ISSUE THREAD

**Issue by Windows81** [DevChatter/devchatterbot#229]
UTC is designed to be supported for the 24 hour format.  Since when did you hear a radiosman say '12am' at 00:00 UTC?

**Comment by benrick** [comment]
This is a great suggestion!

I'd suspect that we want to use the 24 hour format for any UTC+# displays and use the AM/PM approach when another timezone is specified.

I also think this is something that would be a great first issue for someone to improve!
