### ISSUE TITLE
In Hangman We Need a List of Allowed-To-Guess Letters

### ISSUE THREAD

**Issue by benrick** [DevChatter/devchatterbot#265]
We should be sure that characters guessed are within a set of letters possible to appear in our words. We shouldn't allow guessing 1,2,3,ß, etc. to cause a loss in Hangman.

Code for this is mostly in the `HangmanGame` class. We may want to extract this as a `CommandSettingsEntity`.

**Comment by jimbo8098** [comment]
Almost done here.
