### ISSUE TITLE
Add !streams command

### ISSUE THREAD

**Issue by Echostrike36** [DevChatter/devchatterbot#45]
Add !streams command that can be used to highlight other streams. 

maybe if !so is used add that stream to the list that is displayed when !stream is called?

For DevChatter; for example, maybe other C# streams.

This may help to grow the c# community on twitch by promoting other C# streamers.

**Comment by benrick** [comment]
I like that idea. Have you seen what `!so` does when we don't pass it a parameter? It chooses a random stream from among the ones that DevChatter follows. Might be worth getting more specific than that. We did it based on the follow list initially as a convenience.

**Comment by benrick** [comment]
I think this one is resolved now. We need to add more to it, but it's there. Thoughts, @Echostrike36 ?
