### ISSUE TITLE
RPS-Game: When there is no winner, display a more appropriate message.

### ISSUE THREAD

**Issue by asyncawake** [DevChatter/devchatterbot#60]
Right now, when nobody wins, the bot displays the message: "The winners are !" . Another nice enhancement would be to change the message fromt the current "The winners are {name}!" to the more grammatically correct "The winner is  {name}!" when there was only one winner :)

**Comment by benrick** [comment]
We'll be reviewing the changes from TheBoboNL on stream Thursday.
