### ISSUE TITLE
Add IsEnabled property to IBotCommand

### ISSUE THREAD

**Issue by AridTag** [DevChatter/devchatterbot#75]
Should add an IsEnabled (or similar) property to IBotCommand so commands can be registered automatically while retaining the ability to turn specific commands off.

As mentioned on todays stream (2018-04-03)

(The readme mentions that you should make sure to assign the proper label but it looks like non maintainers are unable to do that. Should be flagged as enhancement probably)

**Comment by benrick** [comment]
We'll be doing this one on-stream April 5, 2018.
