### ISSUE TITLE
Add Schedule Command

### ISSUE THREAD

**Issue by benrick** [DevChatter/devchatterbot#81]
Add a `!Schedule` command to the bot to display the regular schedule of the stream.

Would be nice if it converted to a requested timezone.

We started this last stream, but may want to switch to nodatime if it can handle it better. It should support .net standard.

**Comment by benrick** [comment]
We started this one, but anyone's welcome to work on it. If not, I'll get to it soon.

**Comment by jdphenix** [comment]
Should configuration be possible through the command interface (i.e. !schedule add daily MWRFS 14:00-16:00 America/Chicago), or should we look at creating a UI to manage this?

**Comment by benrick** [comment]
We'll eventually want a UI for most of the things that are currently configurable through the command line, however, the usefulness of command line is that mods can assist the streamer by making changes to things like this. I think having both as an option is a good idea.

In fact, I'd expect that many of the commands we create for these sorts of things will be enabled through that UI, so a bot owner could decide to turn those features off.

**Comment by jdphenix** [comment]
It sounds like we're talking about a combination of exposing command metadata and dispatcher. With such an architecture, the interface implementation (be it command line, web, desktop, or other) could principally be: 

* Group commands by categories
  * Expose command metadata per command (permission, words, expected arguments, etc.) 
  * User interface specific code to expose command configuration (UI could draw a tab bar with fieldset per command, command line could expose accepted commands and help interface)

I'll open a new issue when I finish writing the proposal for it. It's out of scope for just making the !schedule command.

**Comment by benrick** [comment]
Need to set up configuration either through database or config.

**Comment by benrick** [comment]
This was resolved by #167 which included db configuration. We can add language-awareness later.
