### ISSUE TITLE
Customizable Command Words

### ISSUE THREAD

**Issue by jdphenix** [DevChatter/devchatterbot#99]
Right now, command words are hardcoded into each command instance. Abstract away command word resolution, to allow support for globalization for command words and allowing users to add their own words to existing commands. 

Thought about this looking at #96

**Comment by jdphenix** [comment]
I'd like to take a crack at implementing this.

**Comment by benrick** [comment]
Perhaps instead, we should allow someone to customize the command words in the database instead. Then each person who runs the bot could choose their command words.

**Comment by jdphenix** [comment]
Generalize this issue to abstracting out how command words are resolved then?

**Comment by benrick** [comment]
Yep. It goes to how we set the list of command words for a command. For now, we could initialize them in a database or a config file.

**Comment by jdphenix** [comment]
Great, sounds good. 🕺

**Comment by benrick** [comment]
We'll probably want to set it up so that the current ones are the "defaults" and they can be overridden with new values. I renamed this issue to "Customizable" to account for this direction.
